### ISSUE TITLE
Possibly support MAF file with all upper case column headers?

### ISSUE THREAD

**Issue by thomasyu888** [genome-nexus/annotation-tools#12]
Some centers submit MAF files with all capitalized headers.  Due to this, in my processing code I actually capitalizes the headers to resolve this issue. 

Do you know if Genome Nexus will annotate a maf file with all capitalized headers?  I know vcf2maf also accepted all capitalized headers.

**Comment by ao508** [comment]
I will need to double check this... off the top of my head I want to say that no, the annotator will not work for these. I will follow up with the answer.

**Comment by ao508** [comment]
@thomasyu888 I annotated a MAF with all uppercase column headers and technically the answer to whether Genome Nexus will annotate these kinds of MAFs is yes HOWEVER, certain columns that are added by the Genome Nexus annotator will be duplicated.. 

The standard MAF headers will be adjusted to their proper casing in the output annotated file. However, there are extra columns that the annotator adds that will basically be duplicated. 

For example, if you are running a MAF through the annotator that has a column "CODONS", then the annotator will generate a file with columns "Codons" and "CODONS". "Codons" is a field that is added by the annotator and "CODONS" is the field that existed in the input file.

I see 2 possible solutions... either (1) adjust the `standardize_mutation_data.py` script to ignore case when resolving data from a MAF (so either HUGO_SYMBOL or Hugo_Symbol) would be treated the same way or (2) adjust the annotator so that duplicate columns are not introduced.

**Comment by thomasyu888** [comment]
Hmm... would `standardize_mutation_data.py` remap the columns?  I feel like this could be cumbersome.

Do you know if Genome Nexus duplicates all of the columns or just the ones it also writes out?  For instance, if the maf file had the column COLUMN_NOT_EXIST, does GenomeNexus write this out?

**Comment by ao508** [comment]
the script does not currently remap uppercase headers to their standard form. 

Genome Nexus would retain a column such as `COLUMN_NOT_EXIST` since it is not part of the standard MAF header and it is not one of the fields that gets added due to annotation.

**Comment by thomasyu888** [comment]
I see, so technically Genome Nexus would retain `HUGO_SYMBOL` because it is not a standard MAF header correct?   Instead of remapping, would it be better to add a flag to Genome Nexus to not retain such columns?

**Comment by ao508** [comment]
HUGO_SYMBOL would be remapped to Hugo_Symbol because the annotator will ignore case for the standard MAF columns

**Comment by thomasyu888** [comment]
Hmmm, I think if we just turned the maf headers uppercase, then we would only have to worry about removing the duplicated columns

**Comment by ao508** [comment]
We won't be changing the casing of the MAF headers on our end as we want to continue following the [MAF specifications](https://docs.gdc.cancer.gov/Encyclopedia/pages/Mutation_Annotation_Format_TCGAv2/#about-maf-specifications). Another thing I would want to consider as well is if you're going to be removing duplicate columns as a post-processing step then you would just need to make sure that you retain a column like "Consequence" and not "CONSEQUENCE" as the former is how the Genome Nexus annotation is going to write out that data during annotation.

**Comment by thomasyu888** [comment]
Thanks, so sounds like the solution for me is to map the column headers to the MAF specifications during an added preprocess step.  I wouldn't just be able to download the MAF and run it through the annotation scripts.

The advantage of this is that I wouldn't need to remove any duplicated columns as all the column headers will all have been remapped.  The downside is that script would have to updated alongside the growing MAF spec.

**Comment by ao508** [comment]
I believe the MAF specs have been stable for several years now, I dont think it'll be changing any time soon as it was defined as part of the TCGA project.

**Comment by thomasyu888** [comment]
Closing and filed an issue for myself.
